<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Sacramento State Course Videos'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')                        
                        ->prependStylesheet($this->basePath() . 'http://www.csus.edu/cached/Colleges/2.0/assets/css/monet-20-styles.css')
                        ->prependStylesheet($this->basePath() . 'http://getbootstrap.com/dist/css/bootstrap.css')
                       ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . 'http://getbootstrap.com/dist/js/bootstrap.js')
                                      ->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js') ?>
                                      
                                      <script src="//ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>

    </head>
    <body>
        
        <div class="container">
            <?php echo $this->content; ?>
            
        </div> <!-- /container -->
        
        <script>
$(function() { 
  var $allVideos = 
      $("object, embed"), 
      $fluidEl = $("figure"); 
  
      $allVideos.each(function() { $(this) 
// jQuery .data does not work on object/embed elements 
.attr('data-aspectRatio', this.height / this.width) .removeAttr('height') .removeAttr('width'); }); 
  
  $(window).resize(function() { var newWidth = $fluidEl.width(); $allVideos.each(function() { var $el = $(this); $el .width(newWidth) .height(newWidth * $el.attr('data-aspectRatio')); }); }).resize(); });
</script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
