<!-- #body container -->
<div class="container" id="container">
 
    <!-- #pageContent -->
    <div id="pageContent">
        <!-- #mainRegionContainer -->
        <div id="mainRegionContainer">
          
            <div class="row headingRegion">
        
                 <h1>Magic,Witchcraft+Religion Videos</h1>  
          </div>

                <div class="row videoRegion">
                  
                    <div class="col-md-8 ss-videoplayer-container" id="osmfcontainer">
                      
                        <script type="text/javascript">
                            swfobject.registerObject("sacstate_video", "10.1.0", "http://www2.csus.edu/video/assets/players/10.1/scripts/expressInstall.swf");
                        </script>
                      
                        <div class="ss-videoplayer backdrop">
                          
                            <object id="sacstate_video" >
                                <param name="movie" value="http://www2.csus.edu/video/assets/players/10.1/SampleMediaPlayback.swf?src=http://www2.csus.edu/video/assets/ams_welcome.m4v" />
                                <param name="allowFullScreen" value="true" />
                                <param name="flashvars" value="poster=http://www2.csus.edu/video/assets/images/billboard-default.png&streamType=live&loop=false&autoPlay=false&playButtonOverlay=true&controlBarAutoHide=true"></param>
                                <!--[if !IE]>-->
                                    <object type="application/x-shockwave-flash" data="http://www2.csus.edu/video/assets/players/10.1/SampleMediaPlayback.swf?src=http://www2.csus.edu/video/assets/ams_welcome.m4v" width="640" height="480">
                                        <param name="allowFullScreen" value="true" />
                                        <param name="flashvars" value="poster=http://www2.csus.edu/video/assets/images/billboard-default.png&streamType=live&loop=false&autoPlay=false&playButtonOverlay=true&controlBarAutoHide=true"></param>
                                    <!--<![endif]-->
                                    <div>
                                        <p>
                                            <video controls  poster="http://www.csus.edu/cached/Colleges/2.0/assets/media/billboard/billboard-default.png">
                                                <source src="http://www2.csus.edu/video/assets/ams_welcome.m4v">Your browser does not support Flash Player 10.1 or the HTML5 video element.</video>
                                        </p>
                                    </div>
                                    <!--[if !IE]>-->
                                    </object>
                                <!--<![endif]-->
                            </object>

                        </div> <!-- backdrop-->

                         <h4 class='video-meta'>This is a text to show under the video some info about the video and course...</h4>
                    </div> <!-- ss-videoplayer-container-->
          
                    <div class="col-md-4 last ss-coursevideos-list" id="course_video_container">
                         <h3>ANTH0013 Videos</h3>
                      
                      <ul>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/30">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 09/04/2013</p>
                                <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/31">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 09/09/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/32">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 09/11/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/33">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 09/16/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/34">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 09/18/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/35">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 09/23/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/36">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 09/25/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/37">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 09/30/2013</p>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/38">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 10/02/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/39">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 10/07/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/40">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 10/09/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/41">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 10/14/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/42">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 10/16/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/43">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 10/21/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/44">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 10/23/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/45">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 10/28/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/46">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 10/30/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/47">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 11/04/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/48">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 11/06/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/49">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 11/11/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/50">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 11/13/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/51">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 11/18/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/52">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 11/20/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/53">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 11/25/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/54">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 11/27/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/55">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 12/02/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/56">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 12/04/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/57">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: MONDAY 12/09/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                            <li class="ss-coursevideos-metadata">
                                 <h4>
        <a href="/video/index/index/cid/100861/sid/1/vid/58">
   Magic,Witchcraft+Religion Section: 1        </a>
 </h4>

                                <p>Available: WEDNESDAY 12/11/2013</p>
                                 <ul class='media'>
                                  <li><a href='/'>audio</a></li>
                                  <li><a href='/'>video</a></li>
                                </ul>
                            </li>
                        </ul>
                         
                    </div><!--ss-coursevideos-list-->
          
                     
       
                </div> <!-- video row -->
  
  <div class="row pagenav-container">
                        <div class="col-md-12">

                            <nav>
                                <ul class='nav nav-justified'>
                                    <li><a href="http://www.csus.edu/videocourses/">Course Videos</a>
                                    </li>
                                    <li><a href="http://www2.csus.edu/video/index/live1/">Live Streaming</a>
                                    </li>
                                    <li><a href="http://www.csus.edu/atcs/tools/digitalmedia/index.stm">Digital Media</a>
                                    </li>
                                    <li><a href="http://www.csus.edu/atcs/tools/mediaserver/index.stm">Faculty Media Server</a>
                                    </li>
                                    <li><a href="http://www.csus.edu/sacct/support.stm">Ask a Consultant</a>
                                    </li>
                                    <li><a href="http://www.csus.edu/irt/ServiceDesk/Support/videostreaming/index.html">Streaming Support</a>
                                    </li>
                                    <li><a href="mailto:servicedesk@csus.edu">Email Service Desk</a>
                                    </li>
                                </ul>
                            </nav>
                            
                        </div> <!-- pageContextNavigation-->
                    </div> <!-- pagenav-container-->
      
  
          
        </div><!-- end #mainRegionContainer -->
   </div> <!-- end #pageContent -->
</div> <!-- end #container -->
